// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvuaasugjhdyoiixodtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dWFhc3VnamhkeW9paXhvZHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDgyMjAsImV4cCI6MjA3MDY4NDIyMH0.u9toqPLUR1Ohv319d_aIh0NhlT199LBsxlVEJNXuIgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});